### PR TITLE
Release 0.6.0 ( Garland )

### PR DESCRIPTION
**Pull request by digitalextremist**
Everything should be in order for '0.6.0' except the jRuby build failure I'm weeding out.

This is mostly collected into #174

### CODE REVIEW

**Comment by digitalextremist** [comment]
:no_entry_sign: jruby is causing the build to fail on `-head` as well as `1.7.19`

@headius this can be tested with the following repro and test script:

https://github.com/digitalextremist/reproductions/blob/master/reel/issue-153.rb
https://github.com/digitalextremist/reproductions/blob/master/reel/test-153.sh

I'm trying to back-track to a point that didn't fail, but I don't think that'll work out so well.

**Comment by digitalextremist** [comment]
Iv'e been running and re-running the tests locally, and determined the build failure is happening at the point of trying to terminate the server. When I put the error output back for jruby, I see it infinitely loops over `IOError: closed stream`.

@headius, the issues I've described of the handshake being botched in `non_block` are still there. This is different -- so it's broken into two separate issues. That's #177 and this different build-related error.

**Comment by digitalextremist** [comment]
Completely isolated `jruby` build error:

In the `#run` loop of `Server::HTTPS` -- if `IOError` is rescued, it will infinitely loop. But this seems to be a `jruby` problem because without any connections hitting the server, it will just immediately start failing.

**Comment by digitalextremist** [comment]
It's throwing `OpenSSL::SSL::SSLError: General SSLEngine problem` also. Intermittently.

**Comment by digitalextremist** [comment]
FYI: UNIX Socket support is supposed to be fixed in `jruby 1.7.19` so the loooooong delayed #123 ought to be safe to merge into this release, and if not, we can disable UNIX Sockets if it's jruby running them, otherwise `unix_server` might as well be abandoned because it's extremely out of sync and unless updated ( as I have ) it will continue to be a dead-end/liability to merge into Reel.

**Comment by digitalextremist** [comment]
@headius says this shouldn't be happening, so I've reported this final glitch to jRuby's team to hopefully get all RVMs included in this 0.6.0 release so it can stand unchanged for a while: jruby/jruby#2750

**Comment by digitalextremist** [comment]
Released 0.6.0.pre1 gem. Waiting for jruby/jruby#2750 before `0.6.0.pre2`.

**Comment by benlangfeld** [comment]
Hey @digitalextremist, what can we do to help get 0.6.0 out? I need https://github.com/celluloid/reel/pull/163; is there any chance that could perhaps go in a 0.5.x release?

**Comment by digitalextremist** [comment]
There's a lot pending across the Celluvoid, but this release is actually likely the most ready except for 0.17+ passes being done. If you can run the 0.6.0 milestone branch with 0.17.2 of Celluloid and Celluloid::IO that'd help. But I'm working toward this too.

**Comment by tarcieri** [comment]
Cleaning house on these

**Pull request closed without merging**
