### PR TITLE
Make master 0.7.0.pre (codename "Marilyn")

### PR DESCRIPTION
**Pull request by tarcieri**

### CODE REVIEW

**Comment by digitalextremist** [comment]
Awesome progress on getting `0.6.0` -- and I see `0.6.5` is being by-passed. But I wonder, what's on our plate that's preventing us from going to `1.0` with `Reel`, as it seems pretty solid-state now, and needing supportive gems more so than revisions, improvements, etc. What do you think @tarcieri?

**Comment by digitalextremist** [comment]
( After reviewing the issue tracker for `Reel` ... it seems if we cleared out the issue tracker of all/most issues, we could be ready for `1.0` ... especially `http/2` support... other than that, `Reel` has been stable and relatively full featured for some time. )

**Comment by tarcieri** [comment]
I think the next release could be 1.0. Let's see what problems people have with this one.

**Comment by digitalextremist** [comment]
Right on @tarcieri. Will reorganize labels accordingly

**Pull request merged**
